---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clavex-clavex-eu-v1alpha1-clavexclient
  failurePolicy: Fail
  name: vclavexclient-v1alpha1.kb.io
  rules:
  - apiGroups:
    - clavex.clavex.eu
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clavexclients
  sideEffects: None
